const LESS_THAN = ':<'
const GREATER_THAN = ':>'
const LESS_THAN_OR_EQUAL = ':<='
const GREATHER_THAN_OR_EQUAL = ':>='
const EQUAL = ':='

const STRING = 'string'
const NUMERIC = 'numeric'

const COMPARISONS = [LESS_THAN, GREATER_THAN, LESS_THAN_OR_EQUAL, GREATHER_THAN_OR_EQUAL, EQUAL]

const VALID_COMPARISONS = {
  STRING: [EQUAL],
  NUMERIC: [LESS_THAN, GREATER_THAN, LESS_THAN_OR_EQUAL, GREATHER_THAN_OR_EQUAL, EQUAL]
}

const JOINS = [' :and: ', ' :or: ']

export {
  STRING,
  NUMERIC,
  LESS_THAN,
  GREATER_THAN,
  LESS_THAN_OR_EQUAL,
  GREATHER_THAN_OR_EQUAL,
  EQUAL,
  COMPARISONS,
  VALID_COMPARISONS,
  JOINS
}
