const BETWEEN = 'between'
const CASE_INSENSITIVE_EQUAL = '='
const CASE_INSENSITIVE_NOT_EQUAL = '!='
const CASE_SENSITIVE_EQUAL = '=='
const CASE_SENSITIVE_NOT_EQUAL = '!=='
const CONTAINS = 'contains'
const EQUAL = '='
const GREATER_THAN = '>'
const GREATER_THAN_OR_EQUAL = '>='
const IMPLICIT = ''
const INCLUSIVE_BETWEEN = 'inbetween'
const IS = 'is'
const LESS_THAN = '<'
const LESS_THAN_OR_EQUAL = '<='
const NOT_EQUAL = '!='
const NUMERIC = 'numeric'
const STRING = 'string'

const COMPARISONS = [
  NOT_EQUAL,
  LESS_THAN,
  GREATER_THAN,
  LESS_THAN_OR_EQUAL,
  GREATER_THAN_OR_EQUAL,
  EQUAL,
  CONTAINS
]

/* SUGGESTION REGEX */

const FACET_SUGGESTION_REGEX = /\w+/gi

/* END SUGGESTION REGEX */

export {
  BETWEEN,
  CASE_INSENSITIVE_EQUAL,
  CASE_INSENSITIVE_NOT_EQUAL,
  CASE_SENSITIVE_EQUAL,
  CASE_SENSITIVE_NOT_EQUAL,
  COMPARISONS,
  CONTAINS,
  EQUAL,
  FACET_SUGGESTION_REGEX,
  GREATER_THAN,
  GREATER_THAN_OR_EQUAL,
  IMPLICIT,
  INCLUSIVE_BETWEEN,
  IS,
  LESS_THAN,
  LESS_THAN_OR_EQUAL,
  NOT_EQUAL,
  NUMERIC,
  STRING
}
